name: WCAG tests

on:
  pull_request:
    branches: [main, develop, hotfix/*, release/*, support/*]

jobs:
  WCAG-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    # Skip post-install scripts here, as a malicious
    # script could steal the NPM_TOKEN.
    - run: npm install --ignore-scripts
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    # `npm rebuild` will run all those post-install scripts for us.
    - run: npm rebuild
    - run: npm run build
    - run: npm run wcag
