name: WCAG tests

on:
  pull_request:
    branches: [main, develop, hotfix/*, release/*, support/*]

jobs:
  call_wcag_test:
    uses: yext/slapshot-reusable-workflows/.github/workflows/wcag_test.yml@v1
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
